/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author ZOMBY
 */
public class V_DatosPersonales extends javax.swing.JFrame {

    /**
     * Creates new form V_DatosPersonales
     */
    public V_DatosPersonales() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt_telefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jt_nombre = new javax.swing.JTextField();
        jt_apellidos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jt_domicilio = new javax.swing.JTextField();
        jcb_sexo = new javax.swing.JComboBox<>();
        jb_mas = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtf_ocupacion = new javax.swing.JTextField();
        jt_domicilio1 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jrb_apRespiratorio = new javax.swing.JRadioButton();
        jrb_aparatoCardio = new javax.swing.JRadioButton();
        jrb_apDigestivo = new javax.swing.JRadioButton();
        jrb_sistemNervioso = new javax.swing.JRadioButton();
        jrb_problemasCardio = new javax.swing.JRadioButton();
        jrb_desmayos = new javax.swing.JRadioButton();
        jrb_vertigos = new javax.swing.JRadioButton();
        jrb_diabetes = new javax.swing.JRadioButton();
        jrb_tiroides = new javax.swing.JRadioButton();
        jrb_fiebreReumatica = new javax.swing.JRadioButton();
        jrb_hipertencion = new javax.swing.JRadioButton();
        jrb_embarazada = new javax.swing.JRadioButton();
        jcb_mesesEmbarazo = new javax.swing.JComboBox<>();
        jcb_fuma = new javax.swing.JRadioButton();
        jrb_alcohol = new javax.swing.JRadioButton();
        jrb_drogas = new javax.swing.JRadioButton();
        jrb_alergias = new javax.swing.JRadioButton();
        jtf_alergias = new javax.swing.JTextField();
        jrb_anti = new javax.swing.JRadioButton();
        jtf_anti = new javax.swing.JTextField();
        jcb_higieneBucal = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jrb_brincomania = new javax.swing.JRadioButton();
        jrb_contracciones = new javax.swing.JRadioButton();
        jrb_habitMoridida = new javax.swing.JRadioButton();
        jrb_respiracionBucal = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jRadioButton21 = new javax.swing.JRadioButton();
        jrb_medicamento = new javax.swing.JRadioButton();
        jrb_hospializado = new javax.swing.JRadioButton();
        jtf_medicamento = new javax.swing.JTextField();
        jtf_hospitalizado = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jRadioButton32 = new javax.swing.JRadioButton();
        jRadioButton33 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        jRadioButton36 = new javax.swing.JRadioButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jl_paradontograma = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmi_archivo = new javax.swing.JMenu();
        jmi_presupuesto = new javax.swing.JMenuItem();
        jmi_credito = new javax.swing.JMenuItem();
        jmi_salir = new javax.swing.JMenuItem();

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("INGRESA LOS DATOS DEL PACIENTE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nombre: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jt_telefono.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 120, 20));

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Apellido Paterno:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("FECHA NACIMIENTO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        jt_nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 170, 20));

        jt_apellidos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jt_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 210, 20));

        jLabel6.setBackground(new java.awt.Color(204, 204, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Domicilio:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        jt_domicilio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jt_domicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 220, 20));

        jcb_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sexo", "F", "M" }));
        jPanel1.add(jcb_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 110, -1));

        jb_mas.setText("AGREGAR");
        jPanel1.add(jb_mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        jLabel12.setBackground(new java.awt.Color(204, 204, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Telefono:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, 20));

        jLabel13.setBackground(new java.awt.Color(204, 204, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("REPRESENTANTE");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 20));

        jtf_ocupacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jtf_ocupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 150, 20));

        jt_domicilio1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jt_domicilio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 220, 20));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 50, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 30, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 30, -1));

        jLabel15.setBackground(new java.awt.Color(204, 204, 255));
        jLabel15.setText("AÑO");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 30, -1));

        jLabel16.setBackground(new java.awt.Color(204, 204, 255));
        jLabel16.setText("DÍA");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 30, -1));

        jLabel17.setBackground(new java.awt.Color(204, 204, 255));
        jLabel17.setText("MES");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 30, -1));

        jLabel18.setBackground(new java.awt.Color(204, 204, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("OCUPACION");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESTADO CIVIL", "CASADO", "SOLTERO" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 150, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESCOLARIDAD", "PREESCOLAR", "PRIMARIA", "SECUNDARIA", "BACHILLERATO", "MEDIA SUPERIOR", "CARRERA", " " }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 310));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("ANTECEDENTES PERSONALES");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jrb_apRespiratorio.setText("Aparato Respiratorio");
        jrb_apRespiratorio.setOpaque(false);
        jPanel2.add(jrb_apRespiratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jrb_aparatoCardio.setText("Aparato Cardiovascular");
        jrb_aparatoCardio.setOpaque(false);
        jPanel2.add(jrb_aparatoCardio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jrb_apDigestivo.setText("Aparato Digestivo");
        jrb_apDigestivo.setOpaque(false);
        jPanel2.add(jrb_apDigestivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jrb_sistemNervioso.setText("Sistema Nervioso");
        jrb_sistemNervioso.setOpaque(false);
        jPanel2.add(jrb_sistemNervioso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jrb_problemasCardio.setText("Probelmas de Goagualacion");
        jrb_problemasCardio.setOpaque(false);
        jPanel2.add(jrb_problemasCardio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jrb_desmayos.setText("Desmayos");
        jrb_desmayos.setOpaque(false);
        jPanel2.add(jrb_desmayos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jrb_vertigos.setText("Vertigos y Mareos");
        jrb_vertigos.setOpaque(false);
        jPanel2.add(jrb_vertigos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jrb_diabetes.setText("Diabetes");
        jrb_diabetes.setOpaque(false);
        jPanel2.add(jrb_diabetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jrb_tiroides.setText("Tiroides");
        jrb_tiroides.setOpaque(false);
        jPanel2.add(jrb_tiroides, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jrb_fiebreReumatica.setText("Fiebre Reumatica");
        jrb_fiebreReumatica.setOpaque(false);
        jPanel2.add(jrb_fiebreReumatica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jrb_hipertencion.setText("Hipertension");
        jrb_hipertencion.setOpaque(false);
        jPanel2.add(jrb_hipertencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jrb_embarazada.setText("Ebarazada");
        jrb_embarazada.setOpaque(false);
        jPanel2.add(jrb_embarazada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        jcb_mesesEmbarazo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Meses", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jPanel2.add(jcb_mesesEmbarazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, -1, -1));

        jcb_fuma.setText("Fuma");
        jcb_fuma.setOpaque(false);
        jPanel2.add(jcb_fuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jrb_alcohol.setText("Bebe Alcohol");
        jrb_alcohol.setFocusable(false);
        jrb_alcohol.setOpaque(false);
        jPanel2.add(jrb_alcohol, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jrb_drogas.setText("Consume Drogas");
        jrb_drogas.setFocusable(false);
        jrb_drogas.setOpaque(false);
        jPanel2.add(jrb_drogas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jrb_alergias.setText("Alergias");
        jrb_alergias.setOpaque(false);
        jPanel2.add(jrb_alergias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));
        jPanel2.add(jtf_alergias, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 140, 20));

        jrb_anti.setText("Anticonceptivo");
        jrb_anti.setOpaque(false);
        jPanel2.add(jrb_anti, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));
        jPanel2.add(jtf_anti, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 140, -1));

        jcb_higieneBucal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Higiene Bucal", "Buena", "Mala" }));
        jPanel2.add(jcb_higieneBucal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 300, 620));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("HABITOS");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jrb_brincomania.setText("Brincomania");
        jrb_brincomania.setOpaque(false);
        jPanel3.add(jrb_brincomania, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jrb_contracciones.setText("Contracciones Musculares");
        jrb_contracciones.setOpaque(false);
        jPanel3.add(jrb_contracciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jrb_habitMoridida.setText("Habitos De Mordida");
        jrb_habitMoridida.setOpaque(false);
        jPanel3.add(jrb_habitMoridida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jrb_respiracionBucal.setText("Respiracion Bucal");
        jrb_respiracionBucal.setOpaque(false);
        jPanel3.add(jrb_respiracionBucal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("EXAMEN DE TEGIDOS");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 20));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentacion", "Buena", "Mala" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jRadioButton21.setText("Esta Bajo Tratamiento");
        jRadioButton21.setOpaque(false);
        jPanel3.add(jRadioButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jrb_medicamento.setText("Toma Medicamento");
        jrb_medicamento.setOpaque(false);
        jPanel3.add(jrb_medicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jrb_hospializado.setText("Ha Sido Hospitalizado");
        jrb_hospializado.setOpaque(false);
        jPanel3.add(jrb_hospializado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));
        jPanel3.add(jtf_medicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 150, -1));
        jPanel3.add(jtf_hospitalizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 150, -1));

        jButton1.setText("Guardar");
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, -1, -1));

        jRadioButton24.setText("Esmalte");
        jRadioButton24.setOpaque(false);
        jPanel3.add(jRadioButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        jRadioButton25.setText("Dentina");
        jRadioButton25.setOpaque(false);
        jPanel3.add(jRadioButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("RX");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        jRadioButton26.setText("Raiz");
        jRadioButton26.setOpaque(false);
        jPanel3.add(jRadioButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        jRadioButton27.setText("Huesos");
        jRadioButton27.setOpaque(false);
        jPanel3.add(jRadioButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("BLANDOS");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jRadioButton28.setText("Encia");
        jRadioButton28.setOpaque(false);
        jPanel3.add(jRadioButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jRadioButton29.setText("Ensercion Epitelial");
        jRadioButton29.setOpaque(false);
        jPanel3.add(jRadioButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jRadioButton30.setText("Lengua");
        jRadioButton30.setOpaque(false);
        jPanel3.add(jRadioButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jRadioButton31.setText("Pulpa Alteraciones");
        jRadioButton31.setOpaque(false);
        jPanel3.add(jRadioButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jRadioButton32.setText("Velo De Paladar");
        jRadioButton32.setOpaque(false);
        jPanel3.add(jRadioButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jRadioButton33.setText("Carrillos");
        jRadioButton33.setOpaque(false);
        jPanel3.add(jRadioButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("CONCLUCIONES");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        jRadioButton34.setText("Morida Abierta");
        jRadioButton34.setOpaque(false);
        jPanel3.add(jRadioButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        jRadioButton35.setText("Desgaste Bruxismo");
        jRadioButton35.setOpaque(false);
        jPanel3.add(jRadioButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        jRadioButton36.setText("Anoclucion");
        jRadioButton36.setOpaque(false);
        jPanel3.add(jRadioButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sobre Mordida", "Horizontal", "Vertical" }));
        jPanel3.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 400, 620));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_paradontograma.setBackground(new java.awt.Color(204, 204, 255));
        jl_paradontograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/odonto.png"))); // NOI18N
        jl_paradontograma.setFocusable(false);
        jl_paradontograma.setRequestFocusEnabled(false);
        jPanel4.add(jl_paradontograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 560, 290));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 580, 300));

        jmi_archivo.setText("Opciones");

        jmi_presupuesto.setText("Presupuesto");
        jmi_archivo.add(jmi_presupuesto);

        jmi_credito.setText("Otorgar Credito");
        jmi_archivo.add(jmi_credito);

        jmi_salir.setText("salir");
        jmi_archivo.add(jmi_salir);

        jMenuBar1.add(jmi_archivo);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_DatosPersonales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_DatosPersonales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_DatosPersonales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_DatosPersonales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_DatosPersonales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton32;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton36;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    public javax.swing.JButton jb_mas;
    private javax.swing.JRadioButton jcb_fuma;
    private javax.swing.JComboBox<String> jcb_higieneBucal;
    public javax.swing.JComboBox<String> jcb_mesesEmbarazo;
    public javax.swing.JComboBox<String> jcb_sexo;
    private javax.swing.JLabel jl_paradontograma;
    public javax.swing.JMenu jmi_archivo;
    public javax.swing.JMenuItem jmi_credito;
    public javax.swing.JMenuItem jmi_presupuesto;
    public javax.swing.JMenuItem jmi_salir;
    private javax.swing.JRadioButton jrb_alcohol;
    public javax.swing.JRadioButton jrb_alergias;
    public javax.swing.JRadioButton jrb_anti;
    private javax.swing.JRadioButton jrb_apDigestivo;
    private javax.swing.JRadioButton jrb_apRespiratorio;
    private javax.swing.JRadioButton jrb_aparatoCardio;
    private javax.swing.JRadioButton jrb_brincomania;
    private javax.swing.JRadioButton jrb_contracciones;
    private javax.swing.JRadioButton jrb_desmayos;
    private javax.swing.JRadioButton jrb_diabetes;
    private javax.swing.JRadioButton jrb_drogas;
    public javax.swing.JRadioButton jrb_embarazada;
    private javax.swing.JRadioButton jrb_fiebreReumatica;
    private javax.swing.JRadioButton jrb_habitMoridida;
    private javax.swing.JRadioButton jrb_hipertencion;
    public javax.swing.JRadioButton jrb_hospializado;
    public javax.swing.JRadioButton jrb_medicamento;
    private javax.swing.JRadioButton jrb_problemasCardio;
    private javax.swing.JRadioButton jrb_respiracionBucal;
    private javax.swing.JRadioButton jrb_sistemNervioso;
    private javax.swing.JRadioButton jrb_tiroides;
    private javax.swing.JRadioButton jrb_vertigos;
    public javax.swing.JTextField jt_apellidos;
    public javax.swing.JTextField jt_domicilio;
    public javax.swing.JTextField jt_domicilio1;
    public javax.swing.JTextField jt_nombre;
    public javax.swing.JTextField jt_telefono;
    public javax.swing.JTextField jtf_alergias;
    public javax.swing.JTextField jtf_anti;
    public javax.swing.JTextField jtf_hospitalizado;
    public javax.swing.JTextField jtf_medicamento;
    public javax.swing.JTextField jtf_ocupacion;
    // End of variables declaration//GEN-END:variables
}
