/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.sun.awt.AWTUtilities;
import java.awt.Font;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZOMBY
 */
public class V_PresupuestoTB extends javax.swing.JFrame {

    public DefaultTableModel defModel;

    /**
     * Creates new form V_PresupuestoTB
     */
    public V_PresupuestoTB() {
        initComponents();
        CustomTable();
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        AWTUtilities.setWindowShape(this, forma);
        this.setLocationRelativeTo(null);
    }

    private void CustomTable() {
        defModel = new DefaultTableModel();
        defModel.addColumn("Concepto");
        defModel.addColumn("Precio");
        defModel.addColumn("Cantidad");
        defModel.addColumn("Total");
        this.jtab_contenido.setModel(defModel);

        if (jtab_contenido.getColumnModel().getColumnCount() > 0) {
            jtab_contenido.getColumnModel().getColumn(0).setPreferredWidth(100);
            jtab_contenido.getColumnModel().getColumn(1).setPreferredWidth(1);
            jtab_contenido.getColumnModel().getColumn(2).setPreferredWidth(1);
            jtab_contenido.getColumnModel().getColumn(3).setPreferredWidth(1);
        }
        jtab_contenido.setFont(new Font("Arial Black", 20, 15));
        jtab_contenido.setRowHeight(30);

        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtab_contenido = new javax.swing.JTable();
        jb_calcular = new javax.swing.JButton();
        jl_nombreCliente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jl_total = new javax.swing.JLabel();
        jb_nuevo = new javax.swing.JButton();
        jb_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanel.setBackground(new java.awt.Color(0, 160, 187));
        jpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtab_contenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtab_contenido);

        jpanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 530, 360));

        jb_calcular.setText("CALCULAR");
        jpanel.add(jb_calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 120, -1));

        jl_nombreCliente.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jl_nombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        jl_nombreCliente.setText("Nombre Cliente");
        jpanel.add(jl_nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TOTAL:");
        jpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, -1));

        jl_total.setFont(new java.awt.Font("Tahoma", 0, 44)); // NOI18N
        jl_total.setForeground(new java.awt.Color(255, 255, 255));
        jl_total.setText("$0.00");
        jpanel.add(jl_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        jb_nuevo.setText("jButton1");
        jpanel.add(jb_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 150, 130));

        jb_salir.setText("salir");
        jpanel.add(jb_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, -1, -1));

        getContentPane().add(jpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_PresupuestoTB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_PresupuestoTB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_PresupuestoTB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_PresupuestoTB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_PresupuestoTB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jb_calcular;
    private javax.swing.JButton jb_nuevo;
    public javax.swing.JButton jb_salir;
    public javax.swing.JLabel jl_nombreCliente;
    public javax.swing.JLabel jl_total;
    private javax.swing.JPanel jpanel;
    public javax.swing.JTable jtab_contenido;
    // End of variables declaration//GEN-END:variables
}
