/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author ZOMBY
 */
public class V_Presupuesto extends javax.swing.JFrame {

    /**
     * Creates new form V_Presupuesto
     */
    public V_Presupuesto() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jl_total = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtf_p_prostotoncia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtf_p_amalgama = new javax.swing.JTextField();
        jtf_p_recina = new javax.swing.JTextField();
        jtf_p_incrustacion = new javax.swing.JTextField();
        jtf_p_corona = new javax.swing.JTextField();
        jtf_p_endodoncia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtf_p_extraccion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtf_p_otro2 = new javax.swing.JTextField();
        jtf_p_limpieza = new javax.swing.JTextField();
        jtf_p_curetas = new javax.swing.JTextField();
        jtf_p_otro1 = new javax.swing.JTextField();
        jtf_c_prostodoncia = new javax.swing.JTextField();
        jtf_c_amalgama = new javax.swing.JTextField();
        jtf_c_recina = new javax.swing.JTextField();
        jtf_c_incrustacion = new javax.swing.JTextField();
        jtf_c_corona = new javax.swing.JTextField();
        jtf_c_endodoncia = new javax.swing.JTextField();
        jtf_c_exraccion = new javax.swing.JTextField();
        jtf_c_otro2 = new javax.swing.JTextField();
        jtf_c_limpieza = new javax.swing.JTextField();
        jtf_c_cureta = new javax.swing.JTextField();
        jtf_c_otro1 = new javax.swing.JTextField();
        jtf_t_prostodoncia = new javax.swing.JTextField();
        jtf_t_amalgama = new javax.swing.JTextField();
        jtf_t_recina = new javax.swing.JTextField();
        jtf_t_incrustacion = new javax.swing.JTextField();
        jtf_t_corona = new javax.swing.JTextField();
        jtf_t_endodoncia = new javax.swing.JTextField();
        jtf_t_exraccion = new javax.swing.JTextField();
        jt_totalNeto = new javax.swing.JTextField();
        jtf_t_limpieza = new javax.swing.JTextField();
        jtf_t_cureta = new javax.swing.JTextField();
        jtf_t_otro1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtf_t_otro2 = new javax.swing.JTextField();
        jb_calcular = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_opciones = new javax.swing.JMenu();
        jmi_generarHistorial = new javax.swing.JMenuItem();
        jmi_cancelar = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("COSTO TOTAL DEL TRATAMIENTO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("INCRUSTACIONES C/U");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("AMALGAMAS C/U");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("EXTRACCIONES C/U");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jl_total.setBackground(new java.awt.Color(204, 204, 255));
        jl_total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_total.setText("TOTAL:");
        jPanel1.add(jl_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        jLabel7.setBackground(new java.awt.Color(204, 204, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("PRECIO");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        jLabel8.setBackground(new java.awt.Color(204, 204, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("ENDODONCIA C/U");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jtf_p_prostotoncia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_p_prostotoncia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 60, -1));

        jLabel9.setBackground(new java.awt.Color(204, 204, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("CORONAS C/U");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel10.setBackground(new java.awt.Color(204, 204, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("CONCEPTO");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel11.setBackground(new java.awt.Color(204, 204, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("PRECIO");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jtf_p_amalgama.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_p_amalgama, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 60, -1));

        jtf_p_recina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_p_recina, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 60, -1));

        jtf_p_incrustacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_p_incrustacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 60, -1));

        jtf_p_corona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_p_corona, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 60, -1));

        jtf_p_endodoncia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_p_endodoncia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 60, -1));

        jLabel12.setBackground(new java.awt.Color(204, 204, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("RECINAS C/U");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel13.setBackground(new java.awt.Color(204, 204, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("PROSTODONCIA C/U");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel14.setBackground(new java.awt.Color(204, 204, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("LIMPIEZA C/U");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel15.setBackground(new java.awt.Color(204, 204, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("CURETAS C/U");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jtf_p_extraccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_p_extraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 60, -1));

        jLabel16.setBackground(new java.awt.Color(204, 204, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("OTRO");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        jtf_p_otro2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_p_otro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 60, -1));

        jtf_p_limpieza.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_p_limpieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 60, -1));

        jtf_p_curetas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_p_curetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 60, -1));

        jtf_p_otro1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_p_otro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 60, -1));

        jtf_c_prostodoncia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_c_prostodoncia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 60, -1));

        jtf_c_amalgama.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_c_amalgama, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 60, -1));

        jtf_c_recina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_c_recina, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 60, -1));

        jtf_c_incrustacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_c_incrustacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 60, -1));

        jtf_c_corona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_c_corona, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 60, -1));

        jtf_c_endodoncia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_c_endodoncia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 60, -1));

        jtf_c_exraccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_c_exraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 60, -1));

        jtf_c_otro2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_c_otro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 60, -1));

        jtf_c_limpieza.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_c_limpieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 60, -1));

        jtf_c_cureta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_c_cureta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 60, -1));

        jtf_c_otro1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_c_otro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 60, -1));

        jtf_t_prostodoncia.setEditable(false);
        jtf_t_prostodoncia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_t_prostodoncia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 120, -1));

        jtf_t_amalgama.setEditable(false);
        jtf_t_amalgama.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_t_amalgama, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 120, -1));

        jtf_t_recina.setEditable(false);
        jtf_t_recina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_t_recina, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 120, -1));

        jtf_t_incrustacion.setEditable(false);
        jtf_t_incrustacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_t_incrustacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 120, -1));

        jtf_t_corona.setEditable(false);
        jtf_t_corona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_t_corona, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 120, -1));

        jtf_t_endodoncia.setEditable(false);
        jtf_t_endodoncia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_t_endodoncia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 120, -1));

        jtf_t_exraccion.setEditable(false);
        jtf_t_exraccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_t_exraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 120, -1));

        jt_totalNeto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jt_totalNeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 120, -1));

        jtf_t_limpieza.setEditable(false);
        jtf_t_limpieza.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_t_limpieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 120, -1));

        jtf_t_cureta.setEditable(false);
        jtf_t_cureta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_t_cureta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 120, -1));

        jtf_t_otro1.setEditable(false);
        jtf_t_otro1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_t_otro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 120, -1));

        jLabel17.setBackground(new java.awt.Color(204, 204, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("OTRO");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        jtf_t_otro2.setEditable(false);
        jtf_t_otro2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jtf_t_otro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 120, -1));

        jb_calcular.setText("CALCULAR");
        jPanel1.add(jb_calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 410, 230, -1));

        jLabel18.setBackground(new java.awt.Color(204, 204, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("CANTIDAD");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 450));

        jm_opciones.setText("Opciones");

        jmi_generarHistorial.setText("Generar Historial Clinico");
        jm_opciones.add(jmi_generarHistorial);

        jmi_cancelar.setText("Cancelar");
        jm_opciones.add(jmi_cancelar);

        jMenuBar1.add(jm_opciones);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Presupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Presupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Presupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Presupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Presupuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jb_calcular;
    private javax.swing.JLabel jl_total;
    public javax.swing.JMenu jm_opciones;
    public javax.swing.JMenuItem jmi_cancelar;
    public javax.swing.JMenuItem jmi_generarHistorial;
    public javax.swing.JTextField jt_totalNeto;
    public javax.swing.JTextField jtf_c_amalgama;
    public javax.swing.JTextField jtf_c_corona;
    public javax.swing.JTextField jtf_c_cureta;
    public javax.swing.JTextField jtf_c_endodoncia;
    public javax.swing.JTextField jtf_c_exraccion;
    public javax.swing.JTextField jtf_c_incrustacion;
    public javax.swing.JTextField jtf_c_limpieza;
    public javax.swing.JTextField jtf_c_otro1;
    public javax.swing.JTextField jtf_c_otro2;
    public javax.swing.JTextField jtf_c_prostodoncia;
    public javax.swing.JTextField jtf_c_recina;
    public javax.swing.JTextField jtf_p_amalgama;
    public javax.swing.JTextField jtf_p_corona;
    public javax.swing.JTextField jtf_p_curetas;
    public javax.swing.JTextField jtf_p_endodoncia;
    public javax.swing.JTextField jtf_p_extraccion;
    public javax.swing.JTextField jtf_p_incrustacion;
    public javax.swing.JTextField jtf_p_limpieza;
    public javax.swing.JTextField jtf_p_otro1;
    public javax.swing.JTextField jtf_p_otro2;
    public javax.swing.JTextField jtf_p_prostotoncia;
    public javax.swing.JTextField jtf_p_recina;
    public javax.swing.JTextField jtf_t_amalgama;
    public javax.swing.JTextField jtf_t_corona;
    public javax.swing.JTextField jtf_t_cureta;
    public javax.swing.JTextField jtf_t_endodoncia;
    public javax.swing.JTextField jtf_t_exraccion;
    public javax.swing.JTextField jtf_t_incrustacion;
    public javax.swing.JTextField jtf_t_limpieza;
    public javax.swing.JTextField jtf_t_otro1;
    public javax.swing.JTextField jtf_t_otro2;
    public javax.swing.JTextField jtf_t_prostodoncia;
    public javax.swing.JTextField jtf_t_recina;
    // End of variables declaration//GEN-END:variables
}
