/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author ZOMBY
 */
public class V_Principal extends javax.swing.JFrame {

    /**
     * Creates new form V_Principal
     */
    public V_Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jb_cerrar_caja = new javax.swing.JButton();
        jb_nuevoPaciente = new javax.swing.JButton();
        jb_buscarPaciente = new javax.swing.JButton();
        jb_agenda = new javax.swing.JButton();
        jb_presupuesto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmi_cerrarCecion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(94, 117, 116));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_cerrar_caja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrar_170_140.png"))); // NOI18N
        jb_cerrar_caja.setText("Cerrar Caja");
        jb_cerrar_caja.setBorder(null);
        jb_cerrar_caja.setBorderPainted(false);
        jb_cerrar_caja.setContentAreaFilled(false);
        jb_cerrar_caja.setFocusPainted(false);
        jb_cerrar_caja.setFocusable(false);
        jPanel1.add(jb_cerrar_caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 170, 140));

        jb_nuevoPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nuevo_170_140.png"))); // NOI18N
        jb_nuevoPaciente.setBorder(null);
        jb_nuevoPaciente.setBorderPainted(false);
        jb_nuevoPaciente.setContentAreaFilled(false);
        jb_nuevoPaciente.setFocusPainted(false);
        jb_nuevoPaciente.setFocusable(false);
        jPanel1.add(jb_nuevoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 170, 140));

        jb_buscarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar_170_140.png"))); // NOI18N
        jb_buscarPaciente.setBorder(null);
        jb_buscarPaciente.setBorderPainted(false);
        jb_buscarPaciente.setContentAreaFilled(false);
        jb_buscarPaciente.setFocusPainted(false);
        jb_buscarPaciente.setFocusable(false);
        jPanel1.add(jb_buscarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 170, 140));

        jb_agenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agenda_170_140.png"))); // NOI18N
        jb_agenda.setBorder(null);
        jb_agenda.setBorderPainted(false);
        jb_agenda.setContentAreaFilled(false);
        jb_agenda.setFocusPainted(false);
        jb_agenda.setFocusable(false);
        jPanel1.add(jb_agenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 170, 140));

        jb_presupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/presupuesto_170_140.png"))); // NOI18N
        jb_presupuesto.setBorder(null);
        jb_presupuesto.setBorderPainted(false);
        jb_presupuesto.setContentAreaFilled(false);
        jb_presupuesto.setFocusPainted(false);
        jb_presupuesto.setFocusable(false);
        jPanel1.add(jb_presupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 170, 140));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cerrar Caja");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 330, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Presupuesto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nuevo Paciente");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Buscar Paciente");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Agenda");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 450));

        jMenu1.setText("Opciones");

        jmi_cerrarCecion.setText("Cerrar Cesion");
        jMenu1.add(jmi_cerrarCecion);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jb_agenda;
    public javax.swing.JButton jb_buscarPaciente;
    public javax.swing.JButton jb_cerrar_caja;
    public javax.swing.JButton jb_nuevoPaciente;
    public javax.swing.JButton jb_presupuesto;
    public javax.swing.JMenuItem jmi_cerrarCecion;
    // End of variables declaration//GEN-END:variables
}
