/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author ZOMBY
 */
public class V_Principal extends javax.swing.JFrame {

    /**
     * Creates new form V_Principal
     */
    public V_Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jb_enTratamiento = new javax.swing.JButton();
        jb_nuevoPaciente = new javax.swing.JButton();
        jb_buscarPaciente = new javax.swing.JButton();
        jb_creditos = new javax.swing.JButton();
        jb_presupuesto = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmi_cerrarCecion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_enTratamiento.setText("TRATAMIENTO");
        jPanel1.add(jb_enTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 200, 120));

        jb_nuevoPaciente.setText("Nuevo Paciente");
        jPanel1.add(jb_nuevoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 200, 120));

        jb_buscarPaciente.setText("Buscar Paciente");
        jPanel1.add(jb_buscarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 200, 120));

        jb_creditos.setText("Agenda");
        jPanel1.add(jb_creditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 200, 120));

        jb_presupuesto.setText("PRESUPUESTO");
        jPanel1.add(jb_presupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 200, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 450));

        jMenu1.setText("Opciones");

        jmi_cerrarCecion.setText("Cerrar Cesion");
        jMenu1.add(jmi_cerrarCecion);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jb_buscarPaciente;
    public javax.swing.JButton jb_creditos;
    public javax.swing.JButton jb_enTratamiento;
    public javax.swing.JButton jb_nuevoPaciente;
    public javax.swing.JButton jb_presupuesto;
    public javax.swing.JMenuItem jmi_cerrarCecion;
    // End of variables declaration//GEN-END:variables
}
