/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.sun.awt.AWTUtilities;
import java.awt.Font;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZOMBY
 */
public class V_Ventas extends javax.swing.JFrame {

    public DefaultTableModel defModel;

    /**
     * Creates new form V_Ventas
     */
    public V_Ventas() {
        initComponents();
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        AWTUtilities.setWindowShape(this, forma);
        customTable();
        this.setLocationRelativeTo(null);
    }

    public void customTable() {
        defModel = new DefaultTableModel();
        defModel.addColumn("Nombre");
        defModel.addColumn("Concepto");
        defModel.addColumn("Precio $");
        defModel.addColumn("Cantidad");
        defModel.addColumn("Total");
        defModel.addColumn("Fecha");
        this.jtab_venta.setModel(defModel);

        if (jtab_venta.getColumnModel().getColumnCount() > 0) {
            jtab_venta.getColumnModel().getColumn(0).setPreferredWidth(50);
            jtab_venta.getColumnModel().getColumn(1).setPreferredWidth(100);
            jtab_venta.getColumnModel().getColumn(2).setPreferredWidth(1);
            jtab_venta.getColumnModel().getColumn(3).setPreferredWidth(1);
            jtab_venta.getColumnModel().getColumn(4).setPreferredWidth(1);
        }
        jtab_venta.setFont(new Font("Arial", 20, 15));
        jtab_venta.setRowHeight(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcbx_filtro = new javax.swing.JComboBox<>();
        jdch_selectFecha = new com.toedter.calendar.JDateChooser();
        jb_bucar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtab_venta = new javax.swing.JTable();
        jb_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 160, 187));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VENTAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jcbx_filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HOY", "TODOS", "BUSCAR OTRA FECHA" }));
        jPanel1.add(jcbx_filtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, 30));

        jdch_selectFecha.setDateFormatString("yyyy-MM-d");
        jPanel1.add(jdch_selectFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 160, 40));

        jb_bucar.setText("buscar");
        jPanel1.add(jb_bucar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jtab_venta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtab_venta);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 780, 530));

        jb_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/regresar.png"))); // NOI18N
        jPanel1.add(jb_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jb_bucar;
    public javax.swing.JButton jb_salir;
    public javax.swing.JComboBox<String> jcbx_filtro;
    public com.toedter.calendar.JDateChooser jdch_selectFecha;
    private javax.swing.JTable jtab_venta;
    // End of variables declaration//GEN-END:variables
}
